[book]
authors = ["kassandra.eth", "Daniel C.", "Marc H."]
language = "en"
multilingual = false
src = "src"
title = "Arrakis Documentation"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
no-section-label = true
additional-css = ["theme/css/img-color-scheme.css", "theme/css/custom-style.css"]

[output.html.fold]
enable = true
level = 0

